# see https://github.com/sigoden/aichat/blob/main/config.example.yaml
#
compress_treshold: 8000

model: litellm:gemini-2.5-pro
clients:

- type: openai-compatible
  name: litellm
  api_base: https://litellm-proxy-1013932759942.europe-west8.run.app
  api_key: 
  models:
    - name: gemini-2.5-pro
    - name: vertex_ai/mistral-small-2503
